-- TEMPO migration 077: remove the retired private starter-feed experiment.
--
-- These exact posts and follow edges were generated by application code for
-- new accounts before they opted into Social. The feature has been removed;
-- this cleanup prevents its placeholder Test Artist-style content from
-- resurfacing when an older private account later joins the network.

delete from profile_follows f
using artist_profiles follower, member_onboarding onboarding
where f.follower_profile_id = follower.id
  and follower.owner_user_id = onboarding.user_id
  and onboarding.starter_community_provisioned_at is not null
  and f.followee_profile_id in (
    select distinct author_profile_id
    from posts
    where scene_id is null
      and visibility = 'followers'
      and media = '[]'::jsonb
      and body in (
        'Welcome to TEMPO. Share what you are making, what you are figuring out, or the next step you want to take.',
        'What is moving in your studio this week? A rough idea counts just as much as a finished release.',
        'Use this feed like an open studio door. Ask for ears, share a small win, or leave a note about the process.'
      )
  );

delete from posts
where scene_id is null
  and visibility = 'followers'
  and media = '[]'::jsonb
  and body in (
    'Welcome to TEMPO. Share what you are making, what you are figuring out, or the next step you want to take.',
    'What is moving in your studio this week? A rough idea counts just as much as a finished release.',
    'Use this feed like an open studio door. Ask for ears, share a small win, or leave a note about the process.'
  );

insert into schema_migrations (version, name, checksum, applied_by)
values (77, '077_remove_synthetic_starter_feed', 'initial', 'migration-self-register')
on conflict (version) do nothing;
