-- TEMPO migration 077: remove the retired private starter-feed experiment.
--
-- These exact posts and follow edges were generated by application code for
-- new accounts before they opted into Social. The feature has been removed;
-- this cleanup prevents its placeholder Test Artist-style content from
-- resurfacing when an older private account later joins the network.

-- Demo workspaces are never members of the real community. Older starter
-- provisioning could select a demo owned by a team/admin account as one of
-- the Green Room's welcome identities.
delete from scene_personas persona
using artist_profiles profile, artists artist
where persona.artist_profile_id = profile.id
  and profile.artist_id = artist.id
  and artist.demo_kind is not null;

-- A demo profile may have been made member-visible by the same retired
-- starter selection. Keep every demo workspace out of real Discover results.
update artist_profiles profile
set visibility = 'private', published_at = null
from artists artist
where profile.artist_id = artist.id
  and artist.demo_kind is not null
  and (profile.visibility <> 'private' or profile.published_at is not null);

-- These accounts came from the retired local Social cast seed. Preserve their
-- data for development history, but remove them from every member-facing
-- discovery surface by making the profiles private.
update artist_profiles
set visibility = 'private', published_at = null
where lower(handle) = any(array[
  'autotuneauntie',
  'basslinebarry',
  'choruscrisis',
  'harmonylawsuit',
  'pluginpriest',
  'softlaunch',
  'velvetstatic'
])
  and (visibility <> 'private' or published_at is not null);

delete from scene_personas persona
using artist_profiles profile
where persona.artist_profile_id = profile.id
  and lower(profile.handle) = any(array[
    'autotuneauntie',
    'basslinebarry',
    'choruscrisis',
    'harmonylawsuit',
    'pluginpriest',
    'softlaunch',
    'velvetstatic'
  ]);

delete from profile_follows follow
using artist_profiles profile
where (follow.follower_profile_id = profile.id or follow.followee_profile_id = profile.id)
  and lower(profile.handle) = any(array[
    'autotuneauntie',
    'basslinebarry',
    'choruscrisis',
    'harmonylawsuit',
    'pluginpriest',
    'softlaunch',
    'velvetstatic'
  ]);

delete from profile_follows f
using artist_profiles follower, member_onboarding onboarding
where f.follower_profile_id = follower.id
  and follower.owner_user_id = onboarding.user_id
  and onboarding.starter_community_provisioned_at is not null
  and f.followee_profile_id in (
    select distinct author_profile_id
    from posts
    where scene_id is null
      and visibility = 'followers'
      and media = '[]'::jsonb
      and body in (
        'Welcome to TEMPO. Share what you are making, what you are figuring out, or the next step you want to take.',
        'What is moving in your studio this week? A rough idea counts just as much as a finished release.',
        'Use this feed like an open studio door. Ask for ears, share a small win, or leave a note about the process.'
      )
  );

delete from posts
where scene_id is null
  and visibility = 'followers'
  and media = '[]'::jsonb
  and body in (
    'Welcome to TEMPO. Share what you are making, what you are figuring out, or the next step you want to take.',
    'What is moving in your studio this week? A rough idea counts just as much as a finished release.',
    'Use this feed like an open studio door. Ask for ears, share a small win, or leave a note about the process.'
  );

insert into schema_migrations (version, name, checksum, applied_by)
values (77, '077_remove_synthetic_starter_feed', 'initial', 'migration-self-register')
on conflict (version) do nothing;
