-- TEMPO migration 107: richer v2 Pro starter kits.
-- Additive and rerunnable. Run after 106.
--
-- Version 1 proved the private, idempotent installation path but each role
-- only contained one visible template. Version 2 gives every role two saved
-- working views, four substantial templates/checklists, and two optional
-- example tasks. New content keys mean someone who tried v1 can add the v2
-- material without changing or overwriting anything they already edited.

begin;

update pro_starter_kits
set status = 'retired'
where version = 1 and status = 'active';

insert into pro_starter_kits(key, version, display_name, home_lens, status) values
  ('manager',2,'Manager','work','active'),
  ('label',2,'Label / label owner','campaigns','active'),
  ('publicist',2,'Publicist','campaigns','active'),
  ('tour_manager',2,'Tour manager','touring','active'),
  ('agent',2,'Agent','schedule','active'),
  ('assistant',2,'Assistant','work','active'),
  ('custom',2,'Custom','custom','active')
on conflict (key, version) do nothing;

insert into pro_starter_kit_definitions
  (kit_key, kit_version, content_key, item_kind, payload, sort_order)
values
  -- Manager: cross-artist decisions, communication, releases, and onboarding.
  ('manager',2,'v2:manager:view:decisions','saved_view',jsonb_build_object('name','Decisions waiting','description','Reviews and decisions that need your call.','surface','work','filters',jsonb_build_object('kind','review','state','open')),10),
  ('manager',2,'v2:manager:view:followups','saved_view',jsonb_build_object('name','Follow-ups across artists','description','Assigned conversations that still need a response.','surface','work','filters',jsonb_build_object('kind','comment','state','open')),20),
  ('manager',2,'v2:manager:template:weekly-review','task_template',jsonb_build_object('name','Weekly artist operating review','description','A Monday reset for priorities, risks, decisions, and communication.','items',to_jsonb(array['Read the artist Team Brief','Review last week''s completed and carried work','Flag overdue deadlines and blocked decisions','Confirm the artist''s top three priorities','Check release, campaign, and show milestones','Assign owners to every open next step','Write the artist-facing weekly summary','Schedule the next operating check-in']::text[])),30),
  ('manager',2,'v2:manager:template:release-decision','checklist_template',jsonb_build_object('name','Release decision brief','description','Turn a release question into a clear, documented decision.','items',to_jsonb(array['State the decision that needs to be made','Collect the current assets and latest version','Summarize audience and campaign context','List timing, budget, and partner constraints','Record the viable options','Recommend one direction and explain why','Name the owner and decision deadline','Share the final decision with everyone affected']::text[])),40),
  ('manager',2,'v2:manager:template:campaign-handoff','checklist_template',jsonb_build_object('name','Campaign handoff','description','A clean transfer between artist, creative, publicity, and release partners.','items',to_jsonb(array['Name the outcome and current campaign phase','Link the approved brief and source assets','Confirm what is finished and what is still open','List every owner and delivery date','Call out approvals still needed','Document risks, dependencies, and fallback plans','Confirm where updates and final files belong','Send the handoff and request acknowledgement']::text[])),50),
  ('manager',2,'v2:manager:template:new-artist','task_template',jsonb_build_object('name','New artist relationship setup','description','Establish the working rhythm before work starts piling up.','items',to_jsonb(array['Read the artist profile and Team Brief','Clarify goals for the next 90 days','Agree on decision rights and communication rhythm','Map the active team and outside partners','Collect current release and campaign calendars','Identify urgent loose ends','Set the first weekly priorities','Book the first operating review']::text[])),60),
  ('manager',2,'v2:manager:sample:priorities','sample_task',jsonb_build_object('title','Prepare Monday priorities for every artist','description','Example of a recurring cross-roster reset.','category','admin'),90),
  ('manager',2,'v2:manager:sample:handoff','sample_task',jsonb_build_object('title','Close the oldest unanswered handoff','description','Example of a small task that restores momentum.','category','admin'),100),

  -- Label: delivery discipline, pitches, release gates, and post-release learning.
  ('label',2,'v2:label:view:approvals','saved_view',jsonb_build_object('name','Release approvals','description','Open release checks and approval decisions.','surface','work','filters',jsonb_build_object('kind','review','state','open')),10),
  ('label',2,'v2:label:view:followups','saved_view',jsonb_build_object('name','Label follow-ups','description','Assigned release and partner tasks across the roster.','surface','work','filters',jsonb_build_object('kind','task','state','open')),20),
  ('label',2,'v2:label:template:release-gate','checklist_template',jsonb_build_object('name','Release readiness gate','description','A final pass before delivery or release-day commitments.','items',to_jsonb(array['Confirm master and clean versions','Verify artist, title, contributor, and rights metadata','Confirm artwork dimensions and final credits','Check ISRC, UPC, splits, and ownership records','Confirm territories, dates, and time zones','Review lyrics, canvas, clips, and platform assets','Confirm distributor delivery and ingestion status','Lock campaign links and pre-save destination','Record unresolved risks and owners','Give a clear ready or not-ready decision']::text[])),30),
  ('label',2,'v2:label:template:dsp-pitch','task_template',jsonb_build_object('name','DSP pitch package','description','Build a concise platform pitch with proof and context.','items',to_jsonb(array['Choose the priority track and pitch window','Write the one-sentence artist and release story','Name genre, mood, culture, and audience signals','Add the strongest early traction or community proof','Call out campaign partners and confirmed moments','Prepare clean links to music, art, and press assets','Tailor the angle for each platform','Log submissions, contacts, and follow-up dates']::text[])),40),
  ('label',2,'v2:label:template:delivery-audit','checklist_template',jsonb_build_object('name','Asset and metadata delivery audit','description','Catch incomplete packages before they become release problems.','items',to_jsonb(array['Inventory every required audio deliverable','Inventory artwork, motion, and social assets','Check filenames and version labels','Validate credits and contributor spelling','Confirm publishing and rights information','Check explicit-content and territory flags','Verify every delivery destination','Record missing items with owners and deadlines','Archive the approved package location']::text[])),50),
  ('label',2,'v2:label:template:post-release','task_template',jsonb_build_object('name','Post-release pulse','description','Capture what happened and what the next week needs.','items',to_jsonb(array['Collect first-week platform and audience signals','Compare results with the release hypothesis','Log playlist, press, radio, and creator support','Identify the strongest audience response','List campaign elements worth extending','Flag metadata or delivery issues','Choose the next three actions','Share a short learning note with the artist']::text[])),60),
  ('label',2,'v2:label:sample:audit','sample_task',jsonb_build_object('title','Audit the next release package','description','Example release-gate work.','category','admin'),90),
  ('label',2,'v2:label:sample:cadence','sample_task',jsonb_build_object('title','Draft a 30-day release cadence','description','Example planning task for the next campaign.','category','production'),100),

  -- Publicist: campaign story, outreach, follow-up, and amplification.
  ('publicist',2,'v2:publicist:view:campaigns','saved_view',jsonb_build_object('name','Open campaign work','description','Every assigned publicity task still in motion.','surface','work','filters',jsonb_build_object('kind','task','state','open')),10),
  ('publicist',2,'v2:publicist:view:approvals','saved_view',jsonb_build_object('name','Copy and asset approvals','description','Reviews that need artist or team feedback.','surface','work','filters',jsonb_build_object('kind','review','state','open')),20),
  ('publicist',2,'v2:publicist:template:kickoff','task_template',jsonb_build_object('name','Press campaign kickoff','description','Build the campaign spine before outreach begins.','items',to_jsonb(array['Define the campaign objective and audience','Write the core artist and release narrative','Collect music, photos, bio, credits, and links','Identify news hooks and timely angles','Segment priority, niche, local, and culture targets','Agree on exclusives and embargo boundaries','Set outreach waves and follow-up dates','Confirm spokesperson availability','Create the coverage and response tracker']::text[])),30),
  ('publicist',2,'v2:publicist:template:pitch-angle','task_template',jsonb_build_object('name','Pitch angle workshop','description','Find several truthful angles instead of sending one generic pitch.','items',to_jsonb(array['Write the plain factual story','Name what is surprising or newly relevant','Find the personal or cultural stakes','Pull three specific proof points','Draft a music-first angle','Draft a local or community angle','Draft a craft or process angle','Match each angle to the right outlet type']::text[])),40),
  ('publicist',2,'v2:publicist:template:outreach','checklist_template',jsonb_build_object('name','Press outreach wave','description','A disciplined send, follow-up, and response cycle.','items',to_jsonb(array['Verify every contact and recent coverage','Personalize the subject and opening line','Use the right pitch angle for the outlet','Check links, embargo, and attachments','Send the first outreach wave','Log sends, opens, replies, and requests','Follow up once with new value','Close the loop on passes and silence','Escalate interview and asset requests quickly']::text[])),50),
  ('publicist',2,'v2:publicist:template:coverage','checklist_template',jsonb_build_object('name','Coverage amplification','description','Turn earned attention into useful campaign momentum.','items',to_jsonb(array['Verify the live link and correct credits','Thank the writer, host, or outlet','Capture an approved quote or clip','Share with the artist and wider team','Prepare platform-specific social versions','Update press highlights and EPK','Notify relevant partners','Log reach, response, and follow-on opportunities']::text[])),60),
  ('publicist',2,'v2:publicist:sample:narrative','sample_task',jsonb_build_object('title','Draft the next campaign narrative','description','Example campaign-foundation task.','category','outreach'),90),
  ('publicist',2,'v2:publicist:sample:targets','sample_task',jsonb_build_object('title','Build a 20-contact priority press list','description','Example outreach preparation.','category','outreach'),100),

  -- Tour manager: advancing, show day, travel, and settlements.
  ('tour_manager',2,'v2:tour:view:advance','saved_view',jsonb_build_object('name','Advance work','description','Open tasks that could block the next shows.','surface','work','filters',jsonb_build_object('kind','task','state','open')),10),
  ('tour_manager',2,'v2:tour:view:decisions','saved_view',jsonb_build_object('name','Tour decisions','description','Reviews and calls that need a tour answer.','surface','work','filters',jsonb_build_object('kind','review','state','open')),20),
  ('tour_manager',2,'v2:tour:template:advance','checklist_template',jsonb_build_object('name','Venue advance','description','The complete pre-show information exchange.','items',to_jsonb(array['Confirm venue, room, address, and local contacts','Confirm load-in, soundcheck, doors, set, and curfew','Exchange stage plot and technical rider','Confirm backline, power, and production exceptions','Confirm guest list, credentials, and security','Confirm dressing rooms, hospitality, and dietary needs','Confirm parking, bus, trailer, and shore power','Confirm merch space, seller, split, and settlement method','Confirm support order and changeovers','Confirm emergency and medical plan','Publish the final day sheet','Get acknowledgement from every department']::text[])),30),
  ('tour_manager',2,'v2:tour:template:show-day','checklist_template',jsonb_build_object('name','Show-day run of show','description','Keep the day moving from arrival through departure.','items',to_jsonb(array['Send the morning day sheet and weather update','Confirm transport and driver call times','Check venue access before arrival','Walk production, hospitality, and dressing rooms','Run soundcheck and document changes','Confirm guest list and merch readiness','Call pre-show milestones','Track set, curfew, and encore timing','Collect settlement and venue paperwork','Confirm load-out and next departure']::text[])),40),
  ('tour_manager',2,'v2:tour:template:travel','checklist_template',jsonb_build_object('name','Travel-day control list','description','Reduce preventable movement-day surprises.','items',to_jsonb(array['Confirm passenger manifest and contacts','Recheck tickets, vehicles, and baggage limits','Confirm passports, visas, and work documents','Share lobby, departure, and arrival times','Check weather and route risks','Confirm hotel rooms and late arrival notes','Name the travel-day decision maker','Send arrival and next-call update']::text[])),50),
  ('tour_manager',2,'v2:tour:template:settlement','checklist_template',jsonb_build_object('name','Show settlement closeout','description','Close the financial and paperwork loop before leaving.','items',to_jsonb(array['Collect ticket counts and deal calculation','Verify guarantees, bonuses, and deductions','Reconcile merch gross, split, and seller fees','Review catering, production, and local expenses','Confirm tax and payment documentation','Receive payment or written payment timing','Photograph or store signed settlement sheets','Share the final summary and flag disputes']::text[])),60),
  ('tour_manager',2,'v2:tour:sample:advance','sample_task',jsonb_build_object('title','Complete the next venue advance','description','Example of the highest-leverage tour task.','category','admin'),90),
  ('tour_manager',2,'v2:tour:sample:daysheet','sample_task',jsonb_build_object('title','Publish tomorrow''s day sheet','description','Example show-operations handoff.','category','admin'),100),

  -- Agent: offers, holds, routing, and confirmed-show handoffs.
  ('agent',2,'v2:agent:view:booking','saved_view',jsonb_build_object('name','Booking follow-ups','description','Open booking tasks and promoter replies.','surface','work','filters',jsonb_build_object('kind','task','state','open')),10),
  ('agent',2,'v2:agent:view:offers','saved_view',jsonb_build_object('name','Offers to decide','description','Open reviews for offers, routing, and terms.','surface','work','filters',jsonb_build_object('kind','review','state','open')),20),
  ('agent',2,'v2:agent:template:offer','checklist_template',jsonb_build_object('name','Offer comparison','description','Compare the real value and risk of competing offers.','items',to_jsonb(array['Normalize date, venue, market, and capacity','Compare guarantee and backend structure','List promoter, support, and billing terms','Estimate travel, production, and tax costs','Check radius, exclusivity, and option clauses','Assess routing and adjacent opportunities','Flag holds, deadlines, and missing terms','Write the recommendation','Record the artist decision']::text[])),30),
  ('agent',2,'v2:agent:template:holds','task_template',jsonb_build_object('name','Hold and deadline follow-up','description','Keep soft dates from disappearing through silence.','items',to_jsonb(array['Confirm the current hold position','Record challenge and expiration deadlines','Ask for missing offer details','Check the artist''s availability and interest','Set the next promoter follow-up','Escalate decisions before the deadline','Release dead holds cleanly','Update the routing picture']::text[])),40),
  ('agent',2,'v2:agent:template:routing','checklist_template',jsonb_build_object('name','Routing sanity check','description','Test whether a run works before committing the artist.','items',to_jsonb(array['Plot every confirmed and held market','Calculate travel time and border constraints','Check rest, press, and production days','Review venue size and market spacing','Estimate transport and lodging exposure','Check radius clauses and competing dates','Identify missing anchor dates','Write the best and fallback route']::text[])),50),
  ('agent',2,'v2:agent:template:handoff','checklist_template',jsonb_build_object('name','Confirmed show handoff','description','Give management and touring a complete booking packet.','items',to_jsonb(array['Store the signed agreement and final offer','Confirm promoter and venue contacts','Record deal, deposit, and settlement terms','Record billing, support, and set length','Add date and deadlines to the shared calendar','Share production and hospitality obligations','Flag visas, tax, insurance, or exclusivity issues','Assign advance ownership','Confirm everyone received the handoff']::text[])),60),
  ('agent',2,'v2:agent:sample:holds','sample_task',jsonb_build_object('title','Clear this week''s expiring holds','description','Example booking-control task.','category','outreach'),90),
  ('agent',2,'v2:agent:sample:route','sample_task',jsonb_build_object('title','Stress-test the next three-show route','description','Example route-planning task.','category','admin'),100),

  -- Assistant: daily control, meetings, handoffs, and weekly close.
  ('assistant',2,'v2:assistant:view:admin','saved_view',jsonb_build_object('name','Admin queue','description','Assigned tasks that keep the operation moving.','surface','work','filters',jsonb_build_object('kind','task','state','open')),10),
  ('assistant',2,'v2:assistant:view:reviews','saved_view',jsonb_build_object('name','Answers to collect','description','Reviews and decisions waiting on follow-through.','surface','work','filters',jsonb_build_object('kind','review','state','open')),20),
  ('assistant',2,'v2:assistant:template:daily-reset','task_template',jsonb_build_object('name','Daily desk reset','description','A calm first pass through priorities, dates, and loose ends.','items',to_jsonb(array['Scan urgent messages and overnight changes','Check today''s calendar and travel','Review overdue and due-today work','Confirm the top three priorities','Prepare links and materials for meetings','Chase one blocked answer','Update owners and dates on changed work','Send a concise morning pulse']::text[])),30),
  ('assistant',2,'v2:assistant:template:meeting','checklist_template',jsonb_build_object('name','Meeting preparation and closeout','description','Make every meeting easier to enter and useful afterward.','items',to_jsonb(array['Confirm attendees, time, and location or link','State the purpose and decisions needed','Collect the latest relevant files','Draft a short agenda','Send pre-read with enough notice','Capture decisions and owners live','Publish notes and deadlines','Schedule follow-ups and file the record']::text[])),40),
  ('assistant',2,'v2:assistant:template:triage','task_template',jsonb_build_object('name','Inbox and handoff triage','description','Turn incoming requests into owned, findable work.','items',to_jsonb(array['Identify the actual ask','Confirm which artist and project it belongs to','Capture the deadline and urgency','Link the source message or file','Assign an owner or ask who owns it','Record the next action','Acknowledge receipt and timing','Close or archive the original thread']::text[])),50),
  ('assistant',2,'v2:assistant:template:weekly-close','checklist_template',jsonb_build_object('name','Weekly admin close','description','Leave the workspace clean enough for Monday.','items',to_jsonb(array['Close completed tasks and stale reminders','Move unfinished work to honest dates','Check next week''s calendar for conflicts','Confirm travel and meeting details','File loose notes, receipts, and assets','List decisions still waiting','Prepare Monday''s first priorities','Send the weekly closeout summary']::text[])),60),
  ('assistant',2,'v2:assistant:sample:morning','sample_task',jsonb_build_object('title','Send today''s three-priority pulse','description','Example daily coordination task.','category','admin'),90),
  ('assistant',2,'v2:assistant:sample:calendar','sample_task',jsonb_build_object('title','Resolve next week''s calendar conflicts','description','Example forward-looking admin task.','category','admin'),100),

  -- Custom: useful general-purpose operating patterns without role assumptions.
  ('custom',2,'v2:custom:view:open','saved_view',jsonb_build_object('name','All open work','description','One clear view of every assigned open item.','surface','work','filters',jsonb_build_object('state','open')),10),
  ('custom',2,'v2:custom:view:decisions','saved_view',jsonb_build_object('name','Decisions and reviews','description','Anything waiting for a considered answer.','surface','work','filters',jsonb_build_object('kind','review','state','open')),20),
  ('custom',2,'v2:custom:template:weekly-reset','task_template',jsonb_build_object('name','Weekly operating reset','description','A flexible review for any professional practice.','items',to_jsonb(array['Review what finished last week','Name what is still open and why','Choose the three outcomes that matter now','Check deadlines and calendar pressure','Identify decisions and dependencies','Assign the next visible action','Protect time for focused work','Share the short weekly plan']::text[])),30),
  ('custom',2,'v2:custom:template:intake','task_template',jsonb_build_object('name','New work intake','description','Turn a loose request into a workable commitment.','items',to_jsonb(array['Write the requested outcome in plain language','Name the artist, project, and stakeholders','Capture the real deadline','Collect source files and reference links','Clarify approval and decision ownership','Estimate effort and dependencies','Define the first deliverable','Confirm the plan with the requester']::text[])),40),
  ('custom',2,'v2:custom:template:decision','checklist_template',jsonb_build_object('name','Decision brief','description','A compact structure for choices that should not live in chat.','items',to_jsonb(array['State the decision and deadline','Explain why it matters now','List known facts and constraints','Describe the viable options','Record risks and tradeoffs','Make a recommendation','Name the final decision owner','Publish the outcome and next action']::text[])),50),
  ('custom',2,'v2:custom:template:handoff','checklist_template',jsonb_build_object('name','Clean handoff','description','Transfer work without losing context or accountability.','items',to_jsonb(array['State what is being handed over','Link the current files and source context','Describe what is done','List what remains open','Name owners and dates','Call out risks and decisions','Confirm where updates belong','Ask the receiver to acknowledge']::text[])),60),
  ('custom',2,'v2:custom:sample:reset','sample_task',jsonb_build_object('title','Run your first weekly operating reset','description','Example of a reusable personal rhythm.','category','admin'),90),
  ('custom',2,'v2:custom:sample:intake','sample_task',jsonb_build_object('title','Turn one loose request into a clear plan','description','Example intake task.','category','other'),100)
on conflict (kit_key, kit_version, content_key) do nothing;

insert into schema_migrations(version, name, checksum, applied_by)
values(107, '107_richer_pro_starter_kits', 'initial', 'migration-self-register')
on conflict(version) do nothing;

commit;
