"use client";

import * as React from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Activity, ArrowLeft, Award, BarChart3, Check, Eye, FileStack, GripVertical, Image as ImageIcon, Layers3, Link2, Plus, Sparkles, Users2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SceneHero } from "@/components/scenes/scene-hero";
import { EmptyShaderPanel } from "@/components/shader-empty";
import { useScene, useSceneMutations } from "@/hooks/use-scenes";
import { useSceneAnalytics, useSceneGroups, useSceneSections, useSceneV2Mutations } from "@/hooks/use-scene-v2";
import type { SceneSectionType } from "@/lib/types";
import { cn, errorMessage } from "@/lib/utils";
import { useToast } from "@/components/ui/toast";
import { SceneStudioContent, SceneStudioInvites, SceneStudioRecognition } from "@/components/scenes/scene-studio-tools";

const TABS = [{ id: "overview", label: "Overview", icon: BarChart3 }, { id: "structure", label: "Structure", icon: Layers3 }, { id: "content", label: "Content", icon: FileStack }, { id: "appearance", label: "Appearance", icon: ImageIcon }, { id: "people", label: "Groups", icon: Users2 }, { id: "recognition", label: "Recognition", icon: Award }, { id: "invites", label: "Invites", icon: Link2 }, { id: "publishing", label: "Public", icon: Eye }] as const;
type Tab = (typeof TABS)[number]["id"];

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="label-mono">{label}</span><span className="mt-2 block">{children}</span></label>; }

export function SceneStudio({ slug }: { slug: string }) {
  const search = useSearchParams();
  const { toast } = useToast();
  const tab = (TABS.some((item) => item.id === search.get("tab")) ? search.get("tab") : "overview") as Tab;
  const { data: sceneData, isLoading } = useScene(slug);
  const scene = sceneData!;
  const { data: sections = [] } = useSceneSections(scene?.id ?? null);
  const { data: groups = [] } = useSceneGroups(scene?.id ?? null);
  const { data: analytics } = useSceneAnalytics(scene?.id ?? null, 30);
  const v2 = useSceneV2Mutations(scene?.id ?? null);
  const legacy = useSceneMutations();
  const [newName, setNewName] = React.useState("");
  const [newType, setNewType] = React.useState<SceneSectionType>("discussion");
  const [groupName, setGroupName] = React.useState("");
  const [focalX, setFocalX] = React.useState(50);
  const [focalY, setFocalY] = React.useState(50);
  React.useEffect(() => { if (scene) { setFocalX(scene.banner_focal_x ?? 50); setFocalY(scene.banner_focal_y ?? 50); } }, [scene]);
  if (isLoading) return <div className="panel h-72 animate-pulse" />;
  if (!scene || (scene.my_role !== "owner" && scene.my_role !== "moderator")) return <EmptyShaderPanel title="Scene Studio is for managers" copy="Owners and moderators can shape the network from here." />;
  const metrics = [{ label: "Active members", value: analytics?.active_members ?? scene.member_count }, { label: "New members", value: analytics?.new_members ?? 0 }, { label: "Posts", value: analytics?.posts ?? 0 }, { label: "Messages", value: analytics?.messages ?? 0 }];
  async function addSection() { if (!newName.trim()) return; try { await v2.createSection.mutateAsync({ sceneId: scene.id, name: newName.trim(), slug: newName.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), type: newType, icon: "sparkles", sortOrder: (sections.length + 1) * 10 }); setNewName(""); toast("Section added.", "ok"); } catch (error) { toast(errorMessage(error, "Couldn't add that section.")); } }
  async function addGroup() { if (!groupName.trim()) return; try { await v2.createGroup.mutateAsync({ sceneId: scene.id, name: groupName.trim(), slug: groupName.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") }); setGroupName(""); toast("Group created.", "ok"); } catch (error) { toast(errorMessage(error, "Couldn't create that group.")); } }
  async function saveAppearance() { try { await legacy.update.mutateAsync({ scene, input: { bannerFocalX: focalX, bannerFocalY: focalY } }); toast("Banner framing saved.", "ok"); } catch (error) { toast(errorMessage(error, "Couldn't save the framing.")); } }
  return <div className="mx-auto max-w-6xl space-y-6"><div><Link href={`/scene/${scene.slug}`} className="inline-flex items-center gap-1.5 text-xs text-text-lo hover:text-ice"><ArrowLeft className="size-3.5" />Back to {scene.name}</Link><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><p className="label-mono">Scene Studio</p><h1 className="mt-1 font-display text-3xl font-semibold text-text-hi">Shape {scene.name}</h1></div><span className="rounded-chip border border-success/25 bg-success/5 px-3 py-1.5 text-xs text-success"><Check className="mr-1 inline size-3" />Network live</span></div></div><nav className="flex gap-1 overflow-x-auto border-b border-line pb-3">{TABS.map(({ id, label, icon: Icon }) => <Link key={id} href={`/scene-studio/${slug}?tab=${id}`} className={cn("inline-flex shrink-0 items-center gap-2 rounded-input px-3 py-2 text-xs", tab === id ? "bg-bg-2 text-ice" : "text-text-lo hover:text-text-hi")}><Icon className="size-3.5" />{label}</Link>)}</nav>
    {tab === "overview" ? <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map((metric) => <div key={metric.label} className="panel-quiet p-4"><p className="font-display text-3xl font-semibold text-text-hi">{metric.value}</p><p className="mt-2 text-xs text-text-lo">{metric.label} · 30 days</p></div>)}</div><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="panel p-5"><div className="flex items-center gap-2"><Activity className="size-4 text-ice" /><h2 className="font-display font-semibold text-text-hi">Network health</h2></div><div className="mt-6 h-44 rounded-panel border border-line bg-[linear-gradient(180deg,color-mix(in_srgb,var(--ice)_10%,transparent),transparent),repeating-linear-gradient(to_right,transparent,transparent_calc(20%-1px),var(--line)_20%)] p-4"><div className="flex h-full items-end gap-2">{[22,34,31,49,42,67,58,74,66,82,76,91].map((height, index) => <div key={index} className="flex-1 rounded-t-sm bg-gradient-to-t from-ice/20 to-ice/70" style={{ height: `${height}%` }} />)}</div></div></div><div className="panel-quiet p-5"><p className="label-mono">Next best moves</p><div className="mt-4 space-y-3">{["Welcome the newest members", "Publish this week's event", "Feature one member project"].map((text) => <div key={text} className="flex items-start gap-2 text-sm text-text-mid"><Sparkles className="mt-0.5 size-3.5 shrink-0 text-amber" />{text}</div>)}</div></div></div></> : null}
    {tab === "structure" ? <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="panel p-5"><p className="label-mono">Navigation</p><h2 className="mt-1 font-display text-xl font-semibold text-text-hi">Sections</h2><div className="mt-5 space-y-2">{sections.map((section, index) => <div key={section.id} className="flex items-center gap-3 rounded-input border border-line bg-bg-1 p-3"><GripVertical className="size-4 text-text-lo" /><div className="grid size-8 place-items-center rounded-input bg-bg-2 text-xs font-semibold text-ice">{index + 1}</div><div className="min-w-0 flex-1"><p className="text-sm font-medium text-text-hi">{section.name}</p><p className="text-[11px] capitalize text-text-lo">{section.type} · {section.visibility}</p></div></div>)}</div></div><div className="panel-quiet p-5"><p className="label-mono">Add a section</p><div className="mt-4 space-y-4"><Field label="Name"><input value={newName} onChange={(event) => setNewName(event.target.value)} placeholder="Resources, Critique, Replays…" className="input w-full" /></Field><Field label="Format"><select value={newType} onChange={(event) => setNewType(event.target.value as SceneSectionType)} className="input w-full">{["discussion","chat","events","library","showcase","page"].map((type) => <option key={type} value={type}>{type}</option>)}</select></Field><Button onClick={() => void addSection()} disabled={!newName.trim() || v2.createSection.isPending} className="w-full"><Plus className="size-4" />Add section</Button></div></div></div> : null}
    {tab === "appearance" ? <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div><SceneHero scene={{ ...scene, banner_focal_x: focalX, banner_focal_y: focalY }} /></div><div className="panel-quiet space-y-5 p-5"><div><p className="label-mono">Banner framing</p><p className="mt-2 text-xs leading-5 text-text-lo">Keep the original image intact and choose the point that should remain visible as the layout adapts.</p></div><Field label={`Horizontal focus · ${focalX}%`}><input type="range" min="0" max="100" value={focalX} onChange={(event) => setFocalX(Number(event.target.value))} className="w-full accent-[var(--ice)]" /></Field><Field label={`Vertical focus · ${focalY}%`}><input type="range" min="0" max="100" value={focalY} onChange={(event) => setFocalY(Number(event.target.value))} className="w-full accent-[var(--ice)]" /></Field><Button onClick={() => void saveAppearance()} disabled={legacy.update.isPending} className="w-full">Save framing</Button><Link href={`/scenes/${scene.slug}/manage/settings`} className="block text-center text-xs text-text-lo hover:text-ice">Change artwork, palette, and details</Link></div></div> : null}
    {tab === "people" ? <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="panel p-5"><p className="label-mono">Access circles</p><h2 className="mt-1 font-display text-xl font-semibold text-text-hi">Groups</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{groups.map((group) => <div key={group.id} className="rounded-panel border border-line bg-bg-1 p-4"><Users2 className="size-4 text-ice" /><p className="mt-4 font-display font-semibold text-text-hi">{group.name}</p><p className="mt-1 text-xs text-text-lo">{group.description || "A focused circle inside this Scene."}</p></div>)}</div></div><div className="panel-quiet p-5"><p className="label-mono">New group</p><input value={groupName} onChange={(event) => setGroupName(event.target.value)} placeholder="Hosts, Cohort A, Editors…" className="input mt-4 w-full" /><Button onClick={() => void addGroup()} disabled={!groupName.trim()} className="mt-3 w-full"><Plus className="size-4" />Create group</Button></div></div> : null}
    {tab === "publishing" ? <div className="panel max-w-2xl p-6"><Eye className="size-5 text-ice" /><h2 className="mt-4 font-display text-xl font-semibold text-text-hi">Public front door</h2><p className="mt-2 text-sm leading-6 text-text-lo">Publish selected pages, events, and showcase work at a clean public URL without exposing member conversations.</p><div className="mt-5 flex gap-2"><Link href={`/s/${scene.slug}`}><Button>Preview public page</Button></Link></div></div> : null}
    {tab === "content" ? <SceneStudioContent scene={scene} /> : null}
    {tab === "recognition" ? <SceneStudioRecognition scene={scene} /> : null}
    {tab === "invites" ? <SceneStudioInvites scene={scene} /> : null}
  </div>;
}
