"use client";

import Link from "next/link";
import { ArrowRight, Plus, Sparkles } from "lucide-react";
import { SceneCard } from "@/components/scenes/scene-card";
import { useMyScenes } from "@/hooks/use-scenes";

export default function SceneHomePage() {
  const { data: scenes = [], isLoading } = useMyScenes();
  return <div className="mx-auto max-w-6xl space-y-8"><section className="relative overflow-hidden rounded-panel border border-line bg-[radial-gradient(circle_at_10%_0%,color-mix(in_srgb,var(--ice)_15%,transparent),transparent_48%),radial-gradient(circle_at_90%_20%,color-mix(in_srgb,var(--amber)_12%,transparent),transparent_50%),var(--bg-1)] p-6 sm:p-9"><div className="scene-hero-grain absolute inset-0 opacity-[0.035]" /><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="label-mono">Scene network</p><h1 className="mt-2 max-w-2xl font-display text-3xl font-semibold tracking-tight text-text-hi sm:text-4xl">A home for the people making things together.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-text-lo">Collectives, writing rooms, labels, local communities, and creative circles—all with their own rhythm.</p></div><Link href="/scenes?create=1" className="inline-flex items-center gap-2 rounded-input bg-ice px-4 py-2.5 text-sm font-medium text-bg-0"><Plus className="size-4" />Create a Scene</Link></div></section><div className="flex items-center justify-between"><div><p className="label-mono">Your places</p><h2 className="mt-1 font-display text-xl font-semibold text-text-hi">My Scenes</h2></div><Link href="/scene?view=discover" className="inline-flex items-center gap-1.5 text-xs text-text-lo hover:text-ice">Discover more<ArrowRight className="size-3.5" /></Link></div>{isLoading ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[0,1,2].map((item) => <div key={item} className="panel h-64 animate-pulse" />)}</div> : scenes.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{scenes.map((scene) => <SceneCard key={scene.id} scene={scene} href={`/scene/${scene.slug}`} />)}</div> : <div className="panel grid min-h-72 place-items-center p-8 text-center"><div><Sparkles className="mx-auto size-6 text-amber" /><h2 className="mt-4 font-display text-xl font-semibold text-text-hi">Your first Scene starts here</h2><p className="mx-auto mt-2 max-w-md text-sm text-text-lo">Create a new network or discover a community already gathering on TEMPO.</p></div></div>}</div>;
}
